# Generated by Django 3.2.9 on 2021-11-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_catalog', '0005_auto_20211102_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='world_premiere',
            field=models.DateField(verbose_name='Премьера в мире'),
        ),
    ]
