# Generated by Django 3.2.9 on 2021-11-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_catalog', '0006_alter_movie_world_premiere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-world_premiere',), 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
    ]
