# Generated by Django 3.2.9 on 2021-11-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_catalog', '0008_movie_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age_limit',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Возрастное ограничение'),
        ),
    ]
