# Generated by Django 3.2.9 on 2021-11-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_catalog', '0009_movie_age_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.PositiveSmallIntegerField(choices=[('zero', 0), ('twelve', 12), ('sixteen', 16), ('eighteen', 18)], default='zero', verbose_name='Возрастное ограничение'),
        ),
    ]
