# Generated by Django 3.2.9 on 2021-11-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_catalog', '0010_alter_movie_age_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(choices=[('zero', '0'), ('twelve', '12'), ('sixteen', '16'), ('eighteen', '18')], default='zero', max_length=10, verbose_name='Возрастное ограничение'),
        ),
    ]
