# Generated by Django 3.2.9 on 2021-11-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_catalog', '0011_alter_movie_age_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(choices=[('0', '0'), ('12', '12'), ('16', '16'), ('18', '18')], default='0', max_length=10, verbose_name='Возрастное ограничение'),
        ),
    ]
