# Generated by Django 3.2.9 on 2021-11-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_catalog', '0014_movie_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
        migrations.AddField(
            model_name='movie',
            name='youtube_url',
            field=models.URLField(default='', verbose_name='Ссылка на трейлер в ютубе'),
        ),
    ]
