# Generated by Django 3.2.9 on 2021-11-16 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_catalog', '0018_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_catalog.rating', verbose_name='Рейтинг'),
        ),
    ]
