# Generated by Django 3.2.9 on 2021-11-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_catalog', '0021_auto_20211116_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Рецензию', 'verbose_name_plural': 'Рецензии'},
        ),
    ]
