# Generated by Django 3.2.9 on 2021-11-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_catalog', '0023_auto_20211116_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-posted_at',), 'verbose_name': 'Рецензию', 'verbose_name_plural': 'Рецензии'},
        ),
        migrations.AlterField(
            model_name='ratingstar',
            name='number',
            field=models.FloatField(default=0, verbose_name='Число'),
        ),
    ]
