# Generated by Django 3.2.9 on 2021-11-16 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_catalog', '0024_auto_20211116_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ('-number',), 'verbose_name': 'Звезду рейтинга', 'verbose_name_plural': 'Звезды рейтинга'},
        ),
        migrations.AlterField(
            model_name='ratingstar',
            name='number',
            field=models.FloatField(default=0, unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Число'),
        ),
    ]
